export { default as Navbar} from "./Navbar";
export { default as FooterComp} from "./FooterComp";
export { default as Home} from "./Home";
export { default as Info} from "./Locations";
export { default as Contact} from "./Contact";
export { default as countryList} from "./countryList";
export { default as VideoComp} from "./VideoComp";
export { default as SimpleForm} from "./FormForContact";
export { default as BusinessCard} from "./businessCard";